name: Python Specification

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python: [3.8, pypy-3.8]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox requests
      - name: Download Geth and add to $PATH
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          $GITHUB_WORKSPACE/linux.py
